name: "bertagent: Build Main"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "bertagent-v[0-9]+.[0-9]+.[0-9]+"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Lint with flake8
        run: |
          flake8 bertagent --count --verbose --show-source --statistics
      - name: Check with black
        run: |
          black --check bertagent
      - name: Test with pytest
        run: |
          pytest
